import { buildDocumentation } from '../../generator/builder';
import { loadConfig } from '../utils/config-loader';
import * as fs from 'fs';
import * as path from 'path';
import { spawn } from 'child_process';
import { copyTemplateToOutput } from '../utils/template-copier';
import { buildWebsiteWithComponents } from '../utils/website-builder';
import { glob } from 'glob';

export interface BuildOptions {
  config: string;
  baseUrl?: string;
  verbose?: boolean;
  enableTypeCheck?: boolean;
}

/**
 * Copy component files to the output directory for live preview
 * This copies ALL component files found by the glob patterns, maintaining directory structure
 */
async function copyComponentsForPreview(
  config: any,
  outputDir: string,
  verbose: boolean
): Promise<number> {
  const previewDir = path.join(outputDir, 'preview-components');

  // Create preview-components directory
  if (!fs.existsSync(previewDir)) {
    fs.mkdirSync(previewDir, { recursive: true });
  }

  let copiedCount = 0;
  const componentMap: Array<{ name: string; path: string; isNamed: boolean }> = [];

  if (verbose) {
    console.log('📦 Copying components for live preview...\n');
  }

  // Extract base directory from the first pattern (e.g., "src/components" from "src/components/**/*.tsx")
  const firstPattern = config.source.include[0];
  const baseDir = firstPattern.replace(/\/\*\*\/.*$/, '').replace(/\/$/, '');

  // Find all component files using the same patterns as the documentation builder
  for (const pattern of config.source.include) {
    const files = await glob(pattern, {
      ignore: config.source.exclude || [],
      cwd: process.cwd(),
    });

    for (const file of files) {
      const sourcePath = path.resolve(process.cwd(), file);

      // Strip the base directory to get relative path (e.g., "layout/LoadingDots/LoadingDots.tsx")
      const relativePath = file.replace(new RegExp(`^${baseDir.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}/`), '');
      const targetPath = path.join(previewDir, relativePath);

      // Create target directory
      const targetDir = path.dirname(targetPath);
      if (!fs.existsSync(targetDir)) {
        fs.mkdirSync(targetDir, { recursive: true });
      }

      // Read file content and strip 'use client' directive
      let content = fs.readFileSync(sourcePath, 'utf-8');
      content = content.replace(/^['"]use client['"];?\s*\n/m, '');

      // Write processed content
      fs.writeFileSync(targetPath, content, 'utf-8');
      copiedCount++;

      if (verbose) {
        console.log(`  ✓ Copied ${file}`);
      }

      // Extract component info for the index
      const fileName = path.basename(file, path.extname(file));

      // Try to find the actual export name from the file content
      let componentName = fileName;
      let isNamed = false;

      // Check for named exports: export const ComponentName or export function ComponentName
      const namedExportMatch = content.match(/export\s+(?:const|function)\s+(\w+)/);
      if (namedExportMatch) {
        componentName = namedExportMatch[1];
        isNamed = true;
      }

      // Check for default export
      const hasDefaultExport = content.includes('export default');
      if (hasDefaultExport && !namedExportMatch) {
        // Default export - use filename as component name
        isNamed = false;
      }

      componentMap.push({
        name: componentName,
        path: './' + relativePath.replace(/\.(tsx|jsx|ts|js)$/, ''),
        isNamed: isNamed
      });
    }
  }

  // Also copy style files
  const styleExtensions = config.source.styleFiles || ['.css', '.scss', '.module.css', '.module.scss'];
  const stylePattern = `**/*{${styleExtensions.join(',')}}`;

  const styleFiles = await glob(stylePattern, {
    cwd: baseDir,
  });

  for (const file of styleFiles) {
    const sourcePath = path.join(baseDir, file);
    const targetPath = path.join(previewDir, file);

    const targetDir = path.dirname(targetPath);
    if (!fs.existsSync(targetDir)) {
      fs.mkdirSync(targetDir, { recursive: true });
    }

    if (fs.existsSync(sourcePath)) {
      fs.copyFileSync(sourcePath, targetPath);
      copiedCount++;

      if (verbose) {
        console.log(`  ✓ Copied ${file}`);
      }
    }
  }

  // Generate index.ts for component imports
  const imports = componentMap
    .map(({ name, path, isNamed }) => {
      if (isNamed) {
        return `import { ${name} } from '${path}';`;
      } else {
        return `import ${name} from '${path}';`;
      }
    })
    .join('\n');

  const exports = componentMap
    .map(({ name }) => `export { ${name} };`)
    .join('\n');

  const componentMapCode = componentMap
    .map(({ name }) => `  '${name}': ${name},`)
    .join('\n');

  const indexContent = `// Auto-generated file - do not edit manually
// This file is generated by DocSpark during the build process

${imports}

${exports}

// Component registry for dynamic imports
export const COMPONENT_MAP: Record<string, any> = {
${componentMapCode}
};
`;

  fs.writeFileSync(path.join(previewDir, 'index.ts'), indexContent, 'utf-8');

  // Generate a component manifest JSON for runtime component checking
  const manifestPath = path.join(outputDir, 'component-manifest.json');
  const manifest = {
    components: componentMap.map(({ name }) => name),
    timestamp: new Date().toISOString()
  };
  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2), 'utf-8');

  if (verbose) {
    console.log(`\n  ✓ Generated index.ts with ${componentMap.length} components`);
    console.log(`  ✓ Generated component-manifest.json`);

    const namedExports = componentMap.filter(c => c.isNamed).map(c => c.name);
    const defaultExports = componentMap.filter(c => !c.isNamed).map(c => c.name);

    if (namedExports.length > 0) {
      console.log(`  ℹ Named exports: ${namedExports.join(', ')}`);
    }
    if (defaultExports.length > 0) {
      console.log(`  ℹ Default exports: ${defaultExports.join(', ')}`);
    }

    console.log(`  ✅ ${copiedCount} files copied for live preview\n`);
  }

  return componentMap.length;
}

/**
 * Run npm test with coverage flag
 */
async function runTestsWithCoverage(verbose: boolean): Promise<boolean> {
  return new Promise((resolve) => {
    console.log('🧪 Running tests with coverage...\n');

    const npmCommand = process.platform === 'win32' ? 'npm.cmd' : 'npm';
    let output = '';

    const testProcess = spawn(npmCommand, ['test', '--', '--coverage', '--watchAll=false'], {
      stdio: verbose ? 'inherit' : 'pipe',
      shell: true,
    });

    // Capture output to check for "No tests found"
    if (!verbose && testProcess.stdout) {
      testProcess.stdout.on('data', (data) => {
        output += data.toString();
      });
    }
    if (!verbose && testProcess.stderr) {
      testProcess.stderr.on('data', (data) => {
        output += data.toString();
      });
    }

    testProcess.on('close', (code) => {
      // Check if no tests were found
      if (output.includes('No tests found') || output.includes('no test specified')) {
        console.warn('⚠️  No tests found. Make sure you have a "test" script in package.json and test files exist.\n');
        console.warn('Continuing with build without coverage data...\n');
        resolve(false);
      } else if (code === 0) {
        console.log('✅ Tests completed successfully\n');
        resolve(true);
      } else {
        console.warn(`⚠️  Tests exited with code ${code}, continuing with build...\n`);
        if (verbose) {
          console.warn('Hint: Make sure your package.json has a valid "test" script configured.\n');
        }
        resolve(false);
      }
    });

    testProcess.on('error', (error) => {
      console.warn(`⚠️  Failed to run tests: ${error.message}`);
      console.warn('Continuing with build without coverage data...\n');
      resolve(false);
    });
  });
}

export async function buildCommand(options: BuildOptions) {
  console.log('📦 Building documentation...\n');

  try {
    const config = await loadConfig(options.config);

    if (options.baseUrl) {
      config.output.baseUrl = options.baseUrl;
    }

    const outputDir = config.output.directory;

    // Always clean output directory before building to prevent old artifacts from accumulating
    if (fs.existsSync(outputDir)) {
      console.log(`🧹 Cleaning ${outputDir}...`);
      fs.rmSync(outputDir, { recursive: true });
    }

    // Create output directory
    fs.mkdirSync(outputDir, { recursive: true });

    console.log(`📖 Project: ${config.name}`);
    console.log(`📂 Source: ${config.source.include.join(', ')}`);
    console.log(`📁 Output: ${outputDir}`);
    console.log(`🔗 Base URL: ${config.output.baseUrl}\n`);

    // Run tests with coverage if enabled in config
    if (config.coverage?.enabled === true) {
      await runTestsWithCoverage(options.verbose || false);
    }

    const result = await buildDocumentation(config, options.verbose);

    // Try to build website with components, fall back to template if website source not available
    console.log('\n🌐 Building documentation website...');
    try {
      // Skip type checking by default (unless --enable-type-check is passed)
      const skipTypeCheck = !options.enableTypeCheck;
      await buildWebsiteWithComponents(config, outputDir, options.verbose || false, skipTypeCheck);
      if (options.verbose) {
        console.log('  ✅ Website built with user components');
      }
    } catch (error) {
      console.warn('\n⚠️  Live preview build failed - documentation will be generated without live component previews');
      console.warn('   All documentation features (props, variants, code examples) remain fully functional.\n');

      // Show error details
      if (error instanceof Error) {
        const errorMessage = error.message;

        // Check for common error patterns
        if (errorMessage.includes('Could not resolve') || errorMessage.includes('Cannot find module')) {
          console.warn('❌ Module Resolution Error:');
          console.warn('   Your components are importing files that are not included in the build.');
          console.warn('');

          // Try to extract module names from error
          const moduleMatch = errorMessage.match(/(?:Could not resolve|Cannot find module)\s+['"]([^'"]+)['"]/);
          if (moduleMatch) {
            console.warn(`   Missing import: "${moduleMatch[1]}"`);
            console.warn('');
          }

          console.warn('💡 To fix this:');
          console.warn('   1. Check your docspark.config.json "source.include" patterns');
          console.warn('   2. Ensure all imported files (components, utilities, types, assets) are included');
          console.warn('   3. Add additional glob patterns to include missing dependencies');
          console.warn('');
          console.warn('   Example config:');
          console.warn('   {');
          console.warn('     "source": {');
          console.warn('       "include": [');
          console.warn('         "src/components/**/*.{tsx,jsx}",');
          console.warn('         "src/utils/**/*.{ts,tsx}",  // Include shared utilities');
          console.warn('         "src/types/**/*.ts"          // Include type definitions');
          console.warn('       ]');
          console.warn('     }');
          console.warn('   }');
        } else if (errorMessage.includes('Module build failed') || errorMessage.includes('SyntaxError')) {
          console.warn('❌ Build Error:');
          console.warn('   There was an error compiling your components.');
          console.warn('');
          console.warn(`   ${errorMessage.split('\n')[0]}`);
          console.warn('');
          console.warn('💡 Check your component files for syntax errors or build issues.');
        } else {
          console.warn('❌ Build Error:');
          console.warn(`   ${errorMessage}`);
        }

        if (options.verbose) {
          console.warn('');
          console.warn('Full error details:');
          console.warn(error.stack || error.message);
        }
      }

      console.warn('\n📋 Falling back to pre-built template (no live previews)...\n');

      // Fall back to template
      await copyTemplateToOutput(outputDir, options.verbose);

      // Copy components for preview
      await copyComponentsForPreview(config, outputDir, options.verbose || false);
    }

    // Safety check: Ensure index.html exists in output directory
    const indexPath = path.join(outputDir, 'index.html');
    if (!fs.existsSync(indexPath)) {
      if (options.verbose) {
        console.warn('  ⚠️  index.html not found after build, copying template...');
      }
      await copyTemplateToOutput(outputDir, options.verbose);

      // Also try to copy components for preview if they weren't already
      const previewDir = path.join(outputDir, 'preview-components');
      if (!fs.existsSync(previewDir)) {
        await copyComponentsForPreview(config, outputDir, options.verbose || false);
      }
    }

    console.log('\n✅ Build complete!');
    console.log(`📄 Generated ${result.componentCount} component pages`);
    console.log(`📊 Total variants: ${result.variantCount}`);
    console.log(`🎨 CSS variables: ${result.cssVariableCount}`);
    console.log(`\n📂 Output: ${path.resolve(outputDir)}`);
    console.log(`💡 Run "docspark serve" to preview your documentation`);
  } catch (error) {
    console.error('❌ Build failed:', error);
    process.exit(1);
  }
}
