import * as fs from 'fs';
import * as path from 'path';
import { glob } from 'glob';
import { spawn } from 'child_process';
import { resolveAllDependencies } from './dependency-resolver';

/**
 * Build the documentation website with user's components
 * This copies the user's components into the website source and builds it
 */
export async function buildWebsiteWithComponents(
  config: any,
  outputDir: string,
  verbose: boolean,
  skipTypeCheck: boolean = false
): Promise<void> {
  // Find website source directory
  const websiteSourceDir = findWebsiteSource();

  if (!websiteSourceDir) {
    throw new Error('Website source directory not found (no package.json or src/ directory)');
  }

  const websitePreviewDir = path.join(websiteSourceDir, 'src', 'preview-components');

  // Clear preview-components directory
  if (fs.existsSync(websitePreviewDir)) {
    fs.rmSync(websitePreviewDir, { recursive: true });
  }
  fs.mkdirSync(websitePreviewDir, { recursive: true });

  // Extract base directory from the first pattern
  const firstPattern = config.source.include[0];
  const baseDir = firstPattern.replace(/\/\*\*\/.*$/, '').replace(/\/$/, '');

  const componentMap: Array<{ name: string; path: string; isNamed: boolean }> = [];

  // Step 1: Find all component files matching patterns
  const componentFiles: string[] = [];
  for (const pattern of config.source.include) {
    const files = await glob(pattern, {
      ignore: config.source.exclude || [],
      cwd: process.cwd(),
    });
    componentFiles.push(...files.map(f => path.resolve(process.cwd(), f)));
  }

  if (verbose) {
    console.log(`  📦 Found ${componentFiles.length} component files`);
    console.log('  🔍 Analyzing dependencies...');
  }

  // Step 2: Automatically resolve all dependencies (imports)
  const allFilesToCopy = resolveAllDependencies(componentFiles, baseDir, verbose);

  if (verbose) {
    console.log(`  ✓ Resolved ${allFilesToCopy.size} total files (including dependencies)`);
  }

  // Step 3: Copy all files (components + dependencies)
  for (const sourcePath of allFilesToCopy) {
    // Calculate relative path from base directory
    const relativePath = path.relative(path.resolve(process.cwd(), baseDir), sourcePath);

    // Skip files outside the base directory (e.g., node_modules)
    if (relativePath.startsWith('..')) {
      continue;
    }

    const targetPath = path.join(websitePreviewDir, relativePath);

    const targetDir = path.dirname(targetPath);
    if (!fs.existsSync(targetDir)) {
      fs.mkdirSync(targetDir, { recursive: true });
    }

    // Read and process content
    let content = fs.readFileSync(sourcePath, 'utf-8');

    // Only strip 'use client' from component files
    if (sourcePath.endsWith('.tsx') || sourcePath.endsWith('.jsx')) {
      content = content.replace(/^['"]use client['"];?\s*\n/m, '');
    }

    fs.writeFileSync(targetPath, content, 'utf-8');

    // Build component map only for originally requested components (not dependencies)
    const isOriginalComponent = componentFiles.some(cf =>
      path.resolve(process.cwd(), cf) === sourcePath
    );

    if (isOriginalComponent && (sourcePath.endsWith('.tsx') || sourcePath.endsWith('.jsx'))) {
      const fileName = path.basename(sourcePath, path.extname(sourcePath));

      // Try to find the actual export name from the file content
      let componentName = fileName;
      let isNamed = false;

      // Check for named exports: export const ComponentName or export function ComponentName
      const namedExportMatch = content.match(/export\s+(?:const|function)\s+(\w+)/);
      if (namedExportMatch) {
        componentName = namedExportMatch[1];
        isNamed = true;
      }

      // Check for default export
      const hasDefaultExport = content.includes('export default');
      if (hasDefaultExport && !namedExportMatch) {
        // Default export - use filename as component name
        isNamed = false;
      }

      componentMap.push({
        name: componentName,
        path: './' + relativePath.replace(/\.(tsx|jsx|ts|js)$/, ''),
        isNamed: isNamed
      });
    }
  }

  // Generate index.ts
  const imports = componentMap.map(({ name, path, isNamed }) =>
    isNamed ? `import { ${name} } from '${path}';` : `import ${name} from '${path}';`
  ).join('\n');

  const exports = componentMap.map(({ name }) => `export { ${name} };`).join('\n');

  const componentMapCode = componentMap.map(({ name }) => `  '${name}': ${name},`).join('\n');

  const indexContent = `// Auto-generated file - do not edit manually
// This file is generated by DocSpark during the build process

${imports}

${exports}

// Component registry for dynamic imports
export const COMPONENT_MAP: Record<string, any> = {
${componentMapCode}
};
`;

  fs.writeFileSync(path.join(websitePreviewDir, 'index.ts'), indexContent, 'utf-8');

  if (verbose) {
    console.log(`  ✓ Copied ${componentMap.length} components to website source`);
  }

  // Install website dependencies if node_modules doesn't exist
  const websiteNodeModules = path.join(websiteSourceDir, 'node_modules');
  if (!fs.existsSync(websiteNodeModules)) {
    if (verbose) {
      console.log('  📦 Installing website dependencies...');
    }
    await installWebsiteDependencies(websiteSourceDir, verbose);
  }

  // Build the React website
  if (verbose) {
    console.log('  🔨 Building React website...');
  }

  // Preserve metadata and themes directories before React build (which overwrites outputDir)
  const metadataDir = path.join(outputDir, 'metadata');
  const themesDir = path.join(outputDir, 'themes');
  const tempDir = path.join(outputDir, '..', '.docspark-temp');

  // Save metadata and themes to temp location
  if (fs.existsSync(metadataDir) || fs.existsSync(themesDir)) {
    fs.mkdirSync(tempDir, { recursive: true });
    if (fs.existsSync(metadataDir)) {
      fs.cpSync(metadataDir, path.join(tempDir, 'metadata'), { recursive: true });
    }
    if (fs.existsSync(themesDir)) {
      fs.cpSync(themesDir, path.join(tempDir, 'themes'), { recursive: true });
    }
  }

  await buildReactWebsite(websiteSourceDir, outputDir, verbose, skipTypeCheck);

  // Restore metadata and themes after React build
  if (fs.existsSync(tempDir)) {
    if (fs.existsSync(path.join(tempDir, 'metadata'))) {
      fs.cpSync(path.join(tempDir, 'metadata'), metadataDir, { recursive: true });
    }
    if (fs.existsSync(path.join(tempDir, 'themes'))) {
      fs.cpSync(path.join(tempDir, 'themes'), themesDir, { recursive: true });
    }
    // Clean up temp directory
    fs.rmSync(tempDir, { recursive: true });
  }
}

/**
 * Find the website source directory
 * Returns the directory only if it contains source files (package.json and src/)
 */
function findWebsiteSource(): string | null {
  // Try local website directory first (development)
  const localWebsite = path.join(process.cwd(), 'website');
  if (isWebsiteSourceDir(localWebsite)) {
    return localWebsite;
  }

  // Try package website directory (production - npm installed)
  const packageWebsite = path.join(__dirname, '../../../website');
  if (isWebsiteSourceDir(packageWebsite)) {
    return packageWebsite;
  }

  return null;
}

/**
 * Check if a directory contains website source files (not just build output)
 */
function isWebsiteSourceDir(dir: string): boolean {
  if (!fs.existsSync(dir)) {
    return false;
  }

  // Must have both package.json and src/ to be a valid source directory
  const hasPackageJson = fs.existsSync(path.join(dir, 'package.json'));
  const hasSrcDir = fs.existsSync(path.join(dir, 'src'));

  return hasPackageJson && hasSrcDir;
}

/**
 * Install website dependencies using npm
 */
function installWebsiteDependencies(websiteDir: string, verbose: boolean): Promise<void> {
  return new Promise((resolve, reject) => {
    const npmCommand = process.platform === 'win32' ? 'npm.cmd' : 'npm';

    const installProcess = spawn(
      npmCommand,
      ['install', '--legacy-peer-deps'],
      {
        cwd: websiteDir,
        stdio: verbose ? 'inherit' : 'pipe',
        shell: true,
      }
    );

    let output = '';

    if (!verbose) {
      installProcess.stdout?.on('data', (data) => {
        output += data.toString();
      });
      installProcess.stderr?.on('data', (data) => {
        output += data.toString();
      });
    }

    installProcess.on('close', (code) => {
      if (code === 0) {
        resolve();
      } else {
        if (!verbose) {
          console.error(output);
        }
        reject(new Error(`npm install failed with code ${code}`));
      }
    });

    installProcess.on('error', (error) => {
      reject(error);
    });
  });
}

/**
 * Build the React website using react-scripts
 */
function buildReactWebsite(websiteDir: string, outputDir: string, verbose: boolean, skipTypeCheck: boolean): Promise<void> {
  return new Promise((resolve, reject) => {
    const npxCommand = process.platform === 'win32' ? 'npx.cmd' : 'npx';

    // Ensure outputDir is absolute
    const absoluteOutputDir = path.isAbsolute(outputDir) ? outputDir : path.resolve(process.cwd(), outputDir);

    const buildProcess = spawn(
      npxCommand,
      ['react-scripts', 'build'],
      {
        cwd: websiteDir,
        env: {
          ...process.env,
          BUILD_PATH: absoluteOutputDir,
          CI: 'true', // Treat warnings as warnings, not errors
          ...(skipTypeCheck ? {
            TSC_COMPILE_ON_ERROR: 'true',  // Allow compilation despite TypeScript errors
            SKIP_PREFLIGHT_CHECK: 'true'    // Skip preflight checks
          } : {})
        },
        stdio: verbose ? 'inherit' : 'pipe',
        shell: true,
      }
    );

    let output = '';

    if (!verbose) {
      buildProcess.stdout?.on('data', (data) => {
        output += data.toString();
      });
      buildProcess.stderr?.on('data', (data) => {
        output += data.toString();
      });
    }

    buildProcess.on('close', (code) => {
      if (code === 0) {
        resolve();
      } else {
        // Parse output for useful error information
        let errorSummary = `Website build failed with code ${code}`;

        // Look for module resolution errors
        const moduleNotFoundMatch = output.match(/Module not found:.*?Error: Can't resolve '([^']+)'/);
        if (moduleNotFoundMatch) {
          errorSummary = `Cannot find module "${moduleNotFoundMatch[1]}"`;
        }

        // Look for TypeScript errors
        const tsErrorMatch = output.match(/TypeScript error in ([^:]+):\s*(.+)/);
        if (tsErrorMatch) {
          errorSummary = `TypeScript error in ${tsErrorMatch[1]}: ${tsErrorMatch[2]}`;
        }

        // Look for compilation errors
        const compileErrorMatch = output.match(/Failed to compile\.\s*\n\s*(.+)/);
        if (compileErrorMatch) {
          errorSummary = compileErrorMatch[1].trim();
        }

        if (!verbose) {
          console.error(output);
        }
        reject(new Error(errorSummary));
      }
    });

    buildProcess.on('error', (error) => {
      reject(error);
    });
  });
}
